// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcNl6FpMGc59AXnE4pgOaosUQ3CM_Q9Ek',
    appId: '1:21437395287:web:44a401dba4ffe280d5ce12',
    messagingSenderId: '21437395287',
    projectId: 'latihan-firebase-f09e2',
    authDomain: 'latihan-firebase-f09e2.firebaseapp.com',
    storageBucket: 'latihan-firebase-f09e2.appspot.com',
    measurementId: 'G-7S1JRB26YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmIzSQz3z4tqxfY82_GEbIkK4DMIBRUw4',
    appId: '1:21437395287:android:ac98c22503274be7d5ce12',
    messagingSenderId: '21437395287',
    projectId: 'latihan-firebase-f09e2',
    storageBucket: 'latihan-firebase-f09e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDUbynG9ALXJUvgnBmb-MCGQVx7jHkVHo',
    appId: '1:21437395287:ios:d8641c1215d5f691d5ce12',
    messagingSenderId: '21437395287',
    projectId: 'latihan-firebase-f09e2',
    storageBucket: 'latihan-firebase-f09e2.appspot.com',
    iosClientId: '21437395287-0lrifc7ng257d6mvf0hv18aa4hdkkhpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiddengems',
  );
}
